apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config
data:
  telegraf.conf: |
    [agent]
      interval = "10s"

    [[inputs.internal]]

    [[outputs.file]]
      files = ["stdout"]
      data_format = "json"
