apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-demo-config
data:
  vector.yaml: |
    data_dir: /var/lib/vector

    api:
      enabled: true
      address: 0.0.0.0:8686
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-demo-sources
data:
  demo.yaml: |
    type: demo_logs
    format: json
    interval: 1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-demo-transforms
data:
  add-demo-field.yaml: |
    type: remap
    inputs:
      - demo
    source: |
      .demo = true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-demo-sinks
data:
  console.yaml: |
    type: console
    inputs:
      - add-demo-field
    target: stdout
    encoding:
      codec: json
